### ISSUE TITLE
cannot import: "github.com/abzicht/gogenericfunc/fun"

### ISSUE THREAD

**Issue by githubhacs** [abzicht/gpsplit#1]
hi, I cannot use this code/module due as it fails to import: `github.com/abzicht/gogenericfunc` 

can this please be made available?

Thanks.

**Comment by abzicht** [comment]
Whoops, thanks for pointing it out! The [repo](https://github.com/abzicht/gogenericfunc) is now public, so I will close the issue. Please try running GPSplit again and raise another issue, if you encounter any further problems.
